---
title: "FAirQ - Novelty Detection"
output: 
  html_document:
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 3
    self_contained: true
author: "Jan Abel (jan.abel@inwt-statistics.de)"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

```{r setup, message=FALSE, warning=FALSE, cache=FALSE, echo=FALSE}
devtools::load_all()

library("GGally")
library("tidyverse")

fig_width <- 12
fig_height <- 12
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = fig_width,
  fig.height = fig_height
)
```

# Descriptive Analysis

```{r load_data}
load("../inst/extdata/data_raw.Rds")

df_grid <- data_raw[["grid"]] %>% select(-c(x, y))
df_grid_bigger_zero <- df_grid %>% filter(wohnortmischnutzung > 0,
                                          kfz_per_24h > 0,
                                          building_density > 0,
                                          nox_h > 0)

n <- df_grid %>% nrow
n_bigger_zero <- df_grid_bigger_zero %>% nrow
```

`summary` all data points:  

- $n$ = `r n`

```{r summary_all_data}
df_grid %>% summary()
```

`summary` all data points bigger than zero:  

- $n$ = `r n_bigger_zero`
- `r round(n_bigger_zero/n * 100, 2)`% of all data points.

```{r summary_data_biger_zero}
df_grid_bigger_zero %>% summary()
```

## Correlation Diagrams

```{r correlation_diagrams}
# Correlogram of all data points
ggpairs(df_grid,
        title = "correlogram of all data points")
# Correlogram of all data points bigger than 0
ggpairs(df_grid_bigger_zero,
        title = "correlogram of all data points bigger than zero")
```

## Histograms

```{r histograms}
ggplot(gather(df_grid), aes(value)) +
  ggtitle(paste("Histogram: all vars, n = ", n)) +
  #geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) +
  geom_histogram(
    bins = 30,
    fill = "#69b3a2",
    color = "#e9ecef",
    alpha = 0.8
  ) +
  facet_wrap( ~ key, scales = 'free_x')

ggplot(gather(df_grid_bigger_zero), aes(value)) +
  ggtitle(paste("Histogram: all vars > 0, n = ", n_bigger_zero)) +
  #geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) +
  geom_histogram(
    bins = 30,
    fill = "#69b3a2",
    color = "#e9ecef",
    alpha = 0.8
  ) +
  facet_wrap( ~ key, scales = 'free_x')
```


