#' Join data with min distances with original raw data
#'
#' This function joins the computed min_distances in data with the
#' original untransformed information data_raw
#'
#' @param data (list of 5) 1. grid, 2. stations
#' 3. selected_vars 4. weights 5. name of pollutant
#' @param data_raw (list of 2) 1. grid, 2. stations
#' @export
join_raw_data <- function(data, data_raw) {
  x <- y <- min_dist <- station_id <- NULL # fix linting
  return(
    list(
      grid = left_join(data[["grid"]] %>% select(x, y, min_dist),
                       data_raw[["grid"]],
                       by = c("x", "y")),
      stations = left_join(data[["stations"]] %>% select(station_id, x, y),
                           data_raw[["grid"]],
                           by = c("x", "y")),
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
  
}

#' Filter Distances
#'
#' This Function filter
#'
#' @param data (list of 5) 1. grid, 2. stations 3. selected_vars 4. weights
#' 5. name of pollutant
#' @param lower_bound (numeric) lower quantile bound in percentage
#' @param upper_bound (numeric) upper quantile bound in percentage
#' @return filtered data (list of 5) 1. grid, 2. stations 3. selected_vars
#' 4. weights 5. name of pollutant
#' @export
filter_distances <- function(data, lower_bound, upper_bound = 1.0) {
  min_dist <- NULL
  
  return(
    list(
      grid = data[["grid"]] %>% filter(between(
        min_dist,
        quantile(min_dist, lower_bound, na.rm = TRUE),
        quantile(min_dist, upper_bound, na.rm = TRUE)
      )),
      stations = data[["stations"]],
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}

#' Add Miminal euclidean distance to grid data
#'
#' @param data (list of 5) 1. grid, 2. stations
#' 3. selected_vars 4. weights 5. name of pollutant
#'
#' @return data (list of 5) 1. grid, 2. stations with minimal euclidean distances
#' and 3. selected_vars 4. weights 5. name of pollutant
#' @export
add_eucl_dist <- function(data) {
  normalized_grid <- data[["grid"]]
  normalized_stations <- data[["stations"]]
  
  
  # Compute Distance Matrix
  dist_mat <- compute_dist_mat(data)
  
  
  # choose smallest distance
  normalized_grid <- normalized_grid %>%
    mutate(min_dist = apply(dist_mat, 1, min))
  
  return(
    list(
      grid = normalized_grid,
      stations = normalized_stations,
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}

#' Multiply variables by weighting factor
#'
#' This function multiplies each variable by a given weighting factor
#' (e.g. derived by variable importance)
#' @param data (list of 4) 1. grid, 2. stations 3. selected_vars 4. weights
#' 5. name of pollutant
#' @return (list of 5) 1. grid, 2. stations with weighting factor
#' 3. selected_vars 4. weights 5. name of pollutant
#' @export
multiply_by_weight <- function(data) {
  x <- y <- station_id <- NULL
  
  data_weighted <- data.frame(x = data[["grid"]]$x,
                              y = data[["grid"]]$y)
  
  # weighting factor is generated by a matrix multiplication with
  # a diagonal matrix. The diagonal elements are the given weights
  dat <- as.matrix(data[["grid"]] %>%
                     select(data[["selected_vars"]]))
  weight <- diag(data[["weights"]])
  prod <- dat %*% weight
  colnames(prod) <- data[["selected_vars"]]
  prod <- as.data.frame(prod)
  data_weighted <- cbind(data_weighted, prod)
  
  return(
    list(
      grid = data_weighted,
      stations = inner_join(
        data[["stations"]] %>%
          select(station_id, x, y),
        data_weighted,
        by = c("x", "y")
      ),
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}

#' Compute Distance Matrix
#'
#' This Function computes a distance matrix between two data.frames with a
#' euclidean distance measure
#' @param data (list of 5) 1. grid, 2. stations 3. selected_vars 4. weights
#' 5. name of pollutant
#' @return dist_mat of Size: rows of grid x rows of stations
compute_dist_mat <- function(data) {
  x <- y <- station_id <- NULL
  
  return(cdist(data[["grid"]] %>%
                 select(-c(x, y)),
               data[["stations"]] %>%
                 select(-c(x, y, station_id))))
}

#' Data Standardization
#'
#' This functions computes a standardization of the, using a given quantile
#'
#' @param data (list of 5) 1. grid, 2. stations 3. selected_vars 4. weights
#' 5. name of pollutant
#' @param quantile (numeric) quantile for standardization
#' @param cutoff (numeric) upper cutoff value
#' @return (list of 5) 1. grid, 2. stations with robust standardized_grid
#' 3. selected_vars 4. weights 5. name of pollutant
#' @export
standardization <- function(data,
                            quantile = 0.95,
                            cutoff = 1.0) {
  x <- y <- station_id <- NULL
  
  my_scale <- function(var) {
    var <- var / quantile(var, quantile)
    var[var > cutoff] <- cutoff
    var
  }
  
  standardized_grid <- data[["grid"]] %>%
    mutate_at(vars(-x, -y), ~ (my_scale(.) %>% as.vector))
  
  return(
    list(
      grid = standardized_grid,
      stations = inner_join(
        data[["stations"]] %>%
          select(station_id, x, y),
        standardized_grid,
        by = c("x", "y")
      ),
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}

#' Drop all grid points that are equal to a station
#'
#' This Function remove all grid points that are equal to a station,
#' but not the stations themself.
#'
#' @param data (list of 5) 1. grid, 2. stations 3. selected_vars 4. weights
#' 5. name of pollutant
#' @return dataFiltered (list of 5) 1. grid, 2. stations
#' 3. selected_vars 4. weights 5. name of pollutant
#' @export
drop_gridpoints_eq_to_station <- function(data) {
  station_id <- NULL
  
  grid <- data[["grid"]]
  stations <- data[["stations"]]
  
  return(
    list(
      grid = rbind(
        # remove stations from grid
        anti_join(grid,
                  stations,
                  by = c("x", "y")) %>%
          # filter out grid points that are like stations
          anti_join(stations,
                    by = colnames(grid)[!colnames(grid) %in% c("x", "y")]),
        # add back stations to set of grid points
        stations %>% select(-station_id)
      ),
      stations = stations,
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}

#' Select variables from grid
#'
#' This function selects the subset of variables stored in selected_vars in the
#' grid and stations dataframe
#'
#' @param data (list of 5) 1. grid, 2. stations 3. selected_vars 4. weights
#'5. name of pollutant
#' @return data (list of 5) 1. grid, 2. stations with selected
#' variables and 3. selected_vars 4. weights 5. name of pollutant
#' @export
select_var_from_data <- function(data) {
  return(
    list(
      grid = data[["grid"]] %>%
        select(c("x", "y", data[["selected_vars"]])),
      stations = data[["stations"]] %>%
        select(c("x", "y", "station_id", data[["selected_vars"]])),
      selected_vars = data[["selected_vars"]],
      weights = data[["weights"]],
      pollutant = data[["pollutant"]]
    )
  )
}


#' Adds information about the feature importance of the Variables
#'
#' This function adds a list with a vector containing the names of the needed
#' variables and a vector containing a weighting factor (e.g. derived from the
#' variable importance) for each variable
#' @param data_raw (list of 2) 1. grid and 2. stations
#' @param var_list (list of 2) 1. selected_vars 2. weights
#' @return data_raw_info (list of 5) 1.grid 2.stations
#' 3. selected_vars 4. weights 5. name of pollutant
#' @export
add_var_info <- function(data_raw, var_list) {
  pollutant <- list(pollutant = deparse(substitute(var_list)))
  return(append(data_raw, append(var_list, pollutant)))
}
